apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: search-service
    spec:
      type: ClusterIP
      clusterIP: None
      selector:
        app: search-service
      ports:
        - name: grpc-access
          protocol: TCP
          port: 80
          targetPort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: players-service
    spec:
      type: ClusterIP
      clusterIP: None
      selector:
        orleans/serviceId: players-silo
      ports:
        - name: grpc-access
          protocol: TCP
          port: 80
          targetPort: 80
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: bot-deployment
      labels:
        orleans/serviceId: bot-silo
    spec:
      replicas: 1
      selector:
        matchLabels:
          orleans/serviceId: bot-silo
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
          labels:
            orleans/serviceId: bot-silo
            orleans/clusterId: bot-silo
        spec:
          serviceAccountName: orleanssilo
          volumes:
            - name: bot-settings
              configMap:
                name: bot-config
          terminationGracePeriodSeconds: 180
          containers:
            - name: bot-silo-container
              image: dantesfoncake/bot:bot_latest
              imagePullPolicy: Always
              ports:
                - containerPort: 11111
                - containerPort: 30000
                - containerPort: 80
              env:
                - name: DiscordClientSettings__Token
                  valueFrom:
                    secretKeyRef:
                      name: discord
                      key: token
                - name: SearchServiceClientSettings__ServiceUrl
                  value: http://search-service.default:80
                - name: PlayerServiceClientSettings__ServiceUrl
                  value: http://players-service.default:80
                - name: ORLEANS_SERVICE_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['orleans/serviceId']
                - name: ORLEANS_CLUSTER_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['orleans/clusterId']
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
                  value: "120"
                - name: MongoSettings__ConnectionString
                  valueFrom:
                    secretKeyRef:
                      name: mongo
                      key: connection_string
              volumeMounts:
                - name: bot-settings
                  mountPath: /app/appsettings.json
                  subPath: appsettings.json
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "1000Mi"
                  cpu: "1"
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: bot-silo-hpa
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: bot-deployment
      minReplicas: 1
      maxReplicas: 10
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 85
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 90